apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name}}-secrets
  namespace: {{ .Values.namespace}}
type: Opaque
data:
{{- range $key, $val := .Values.mysql.secrets}}
  {{ $key | upper}}: {{ $val | b64enc | quote}}
{{- end }}
