global:
  namespace: todoapp

todoapp:
  secret:
    secret-key: "@e2(yx)v&tgh3_s=0yja-i!dpebxsz^dg47x)-k&kq_3zf*9e*"
    db-name: "app_db"
    db-user: "app_user"
    db-password: "1234"
    db-host: "mysql-0.mysql.mysql.svc.cluster.local"
  resources:
    requests:
      cpu: "150m"
      memory: "256Mi"
    limits:
      cpu: "150m"
      memory: "256Mi"

  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1

  affinity:
    nodeAffinity:
      key: app
      values: todoapp

image:
  todoapp:
    repository: ikulyk404/todoapp
    tag: "4.0.1"

hpa:
  todoapp:
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 70
    memoryUtilization: 70

persistentVolume:
  todoapp:
    capacity: "1Gi"

persistentVolumeClaim:
  todoapp:
    storage: "1Gi"

serviceAccount: todoapp
