apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.todoapp.secret }}
  {{ $k | upper}}: {{ $v | b64enc | quote }}
{{- end }}
